apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-flask
  namespace: flask
  labels:
    app: python
    component: py-flask
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: python
      component: py-flask
  template:
    metadata:
      labels:
        app: python
        component: py-flask
        logenable: 'true'
    spec:
      terminationGracePeriodSeconds: 40
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 20
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  component: py-flask
              topologyKey: kubernetes.io/hostname
      containers:
        - name: py-flask
          image: IMG_NAME
          resources:
            requests:
              memory: 1Gi
              cpu: '1'
            limits:
              memory: 2Gi
              cpu: '2'
          startupProbe:
            httpGet:
              path: /
              port: 8000
            failureThreshold: 30
            timeoutSeconds: 20
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            timeoutSeconds: 20
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            timeoutSeconds: 20
            periodSeconds: 10
